### ISSUE TITLE
Add Aggie Pride - Worldwide message

### ISSUE THREAD

**Issue by mkc2mkc** [NCATComp410/comp410_summer2020#1]
Requirement: ReqAggiePrideMessage

Size: Small

Description: When demo.py is executed the Aggie Pride - Worldwide! message should be printed. 

Definition of Done:
- [ ] Requirement Defined
- [ ] Design & Implementation
- [ ] Unit Testing

**Comment by orekunrin** [comment]
Implement dataframe_list in find_related_cols_by_name for a [Windows](https://github.com/NCATComp410/comp410_summer2020/issues/28) machine

**Comment by claesmk** [comment]
Hi @orekunrin it looks like the last comment you added to this user-story was a mistake?  This user-story is to add the Aggie Pride message

**Comment by mkc2mkc** [comment]
https://github.com/NCATComp410/comp410_summer2020/pull/38
