### ISSUE TITLE
Implement dataframe_list in find_related_cols_by_content

### ISSUE THREAD

**Issue by cmtaylo3** [NCATComp410/comp410_summer2020#19]

**Comment by cmtaylo3** [comment]
Assigned to self

**Comment by cmtaylo3** [comment]
dataframe_list
#     List of pandas dataframe objects

**Comment by claesmk** [comment]
Did you mean to remove this from the project?

**Comment by cmtaylo3** [comment]
Yes. I was confused on the assignment and what function my team is supposed to be working on. However, I made another issue and rectified it - I believe.

**Comment by claesmk** [comment]
OK, it looks like you created [this new issue](https://github.com/NCATComp410/comp410_summer2020/issues/23) which is fine.  Please go ahead and close this issue so we don't have a duplicate. Don't hesitate to reach out whenever you have a question.  I'll get back to you as soon as I can.
