### ISSUE TITLE
Implement follow_symlink in load_csv_to_df() 

### ISSUE THREAD

**Issue by AntoniaLoyd** [NCATComp410/comp410_summer2020#24]
# follow_symlink
    #     True  = Follow any symbolic links
    #     False = Do not follow symbolic links

**Comment by claesmk** [comment]
Please add a label for your team name and also a label to indicate if you think the effort is small, medium, or large.  Please also assign the issue to yourself and add it to the [project](https://github.com/orgs/NCATComp410/projects/1)

**Comment by AntoniaLoyd** [comment]
This is a bit broad, but what direction exactly should I be taking in follow_symlink. I was initially under the impression that I should be creating symbolic_links, but I am now confused by what "Follow any symbolic links" means. Could u explain this for me.

**Comment by claesmk** [comment]
Hi @AntoniaLoyd,

If you look at the [documentation](https://docs.python.org/3/library/os.html) for os.walk() you'll see a function definition that looks like this:
```
os.walk(top, topdown=True, onerror=None, followlinks=False)
```
The intent of your requirement is to implement the followlinks feature in os.walk()
- If the user sets follow_symlink=True, then os.walk() should attempt to follow links looking for any .csv files.  
- If follow_symlink=False, then you should not follow symbolic links.  

Here is some more information about [symlinks](https://www.switchingtomac.com/tutorials/osx/how-to-create-symlinks-on-your-mac/) on a Mac.

**Comment by AntoniaLoyd** [comment]
Thanks for the explanation and documentation. I'm new to python, but I've started coding and want to know if I'm moving in the right direction so far. 
![Screenshot (21)](https://user-images.githubusercontent.com/42418450/85526521-151ce500-b5d8-11ea-8463-4c987b8b39b8.png)

Am I taking the right approach?

**Comment by claesmk** [comment]
Yes this looks very good.  Now what you'll want to eventually do is integrate this into the other work being done see [this](https://github.com/orgs/NCATComp410/teams/avengers/discussions/8) post - look near the bottom.  Do you see how your code would best integrate into this approach?

One more thing - you will need to actually demo and test this.  Are you using a Mac or a PC or Linux?  The approach would be slightly different.  You'll want to create a symlink in the data directory, show in your demo that the code will either follow or not follow the symlink depending on the True/False setting.

**Comment by AntoniaLoyd** [comment]
Sorry about the late replies. Thanks for the insight and I’m actually using
a PC.

**Comment by AntoniaLoyd** [comment]
Im confused on how I would create symlink in the data directory would I be
hard coding this?

**Comment by AntoniaLoyd** [comment]
I believe I have now gained a better grasp of symlinks. From your last
response I’m assuming there needs to be a directory and files relationship
between the symlink with data acting as the directory. Is this correct?

**Comment by claesmk** [comment]
Please make sure you are looking at your team's discussion space - especially [this](https://github.com/orgs/NCATComp410/teams/avengers/discussions/8) discussion.  There is a placeholder there for the follow_symlink parameter.

**Comment by AntoniaLoyd** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/42418450/85765399-10455780-b6e4-11ea-94b3-5a3c8b70818c.png)
Ive changed my code to create a symlink between data. Data is acting as the src, but Im not sure what would act as the destination among csv files. Could you inform on this?

**Comment by claesmk** [comment]
Hi @AntoniaLoyd 

The way I would do it would be to move one of the csv files to a different location on your local drive, then create a symlink inside your repo to the file you moved.

**Comment by claesmk** [comment]
Correction - I didn't say that right - I meant to say directory

The way I would do it would be to move one of the csv file directories to a different location on your local drive, then create a symlink inside your repo to the directory you moved.

You could also create a totally different data directory and use that

**Comment by claesmk** [comment]
This was difficult to implement on a PC so will close this issue from now and remove this requirement

**Comment by AntoniaLoyd** [comment]
This issue has now been closed, but I wanted to know if it could possibly be reopened. What I have coded is showing no errors, but it still needs to be tested.

**Comment by claesmk** [comment]
OK, just let me know when you have some code to review

**Comment by AntoniaLoyd** [comment]
Ok, will do. Also in the past you mentioned creating a symlink in the repository. I was just kinda confused on how I could go about adding a new data directory to the repository in order for my coded symlink to work.
