### ISSUE TITLE
Make pecan_cookies_load_data() current working directory safe

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_summer2020#46]
As noted in my comment, if you call this function from an alternate current working directory it will fail like this:

```
E   FileNotFoundError: [Errno 2] File ./data/airports/airports.csv does not exist: './data/airports/airports.csv'

pandas/_libs/parsers.pyx:674: FileNotFoundError
```

Please take a look at [this](https://github.com/NCATComp410/comp410_summer2020/blob/6fe66590d7dd682bce0be5b4dc0e58dab56348f0/dfstools/tests/test_relationship_tools.py#L44) implementation and see if you can improve your code to make it cwd safe

**Comment by Jsostmann** [comment]
Thanks for creating the issue for this. Ill get working on revising this function
